### ISSUE TITLE
Is the by-resource option functional?

### ISSUE THREAD

**Issue by Wizofgoz** [cloudcreativity/laravel-json-api#169]
I'm trying to generate my resources via artisan with the by-resource option set to false but it is creating the same class names in the same namespaces and throws an exception. I would think it would be expecting the class name to be the same as the underlying model but wanted to be sure (i.e. User model => User adapter).

I went looking in the code to determine what class names would be expected but couldn't find any places that use that option other than the artisan generators.

**Comment by lindyhopchris** [comment]
Hi! This should be working so thanks for reporting. I'll look into it shortly. What version are you using?

**Comment by lindyhopchris** [comment]
Quick note: tested on the `1.0.0-alpha.1` branch and it's working on that branch. Need to check on `0.12`

**Comment by Wizofgoz** [comment]
ok, I am on `0.12` but it's good to hear that it's working on `1.0.0-alpha.1`

**Comment by Wizofgoz** [comment]
@lindyhopchris are you sure it's working on `1.0.0-alpha.1`? I just migrated to that branch and it's still happening.

When using `php artisan make:json-api:resource` with the following in the json-api config file:
`'by-resource' => false, 'use-eloquent' => true,`

The correct file names are generated but the underlying class names are incorrect (Adapters/User.php houses 'Adapter' class instead of 'User')

**Comment by lindyhopchris** [comment]
Ah, ok I might have misinterpreted what you meant! I thought you meant the file name was wrong rather than the class name. I'll double check (will be tomorrow) and fix.

As a side note, it hasn't been a waste of time upgrading to the alpha.1 branch as I'll be tagging that early next week.
